In [49]:
import pandas as pd
import tqdm
import datetime

In [50]:
# import and format the data
df = pd.read_csv('/Users/andy/Desktop/Netflix 2020 w IMDB Ratings.csv')
df['CleanDate'] = pd.to_datetime(df['CleanDate'])
df['CleanDate'] = df['CleanDate'].dt.date
df['Originals'] = df['Originals'].astype('category')
df['DevDate'] = df['DevDate'].astype('category')
df['Type'] = df['Type'].astype('category')
df['Y'] = df['Y'].astype('category')
df['Country'] = df['Country'].astype('category')

In [51]:
# import a second dataframe with the other dataset that contains genres
genres = pd.read_csv('/Users/andy/Desktop/US Netflix Data - One Row Per Genre.csv')
genres['DATE'] = pd.to_datetime(genres['DATE'])
genres['DATE'] = genres['DATE'].dt.date
genres['GENRES'] = genres['GENRES'].astype('category')
genres['TYPE'] = genres['TYPE'].astype('category')

# rename the imdbtag column so its the same as the other dataframe
genres = genres.rename(columns={'IMDBTag': 'imdbtag'})

In [52]:
# add the genre column from the other dataframe to the main dataframe so that every movie/tv show has a genre (joining on imdbtag)
df = pd.merge(df,genres[['imdbtag','GENRES']],on='imdbtag')

In [53]:
# make the genre the same format as the other columns and put the column in the right place
df = df.rename(columns={'GENRES':'Genre'})
cols = ['Unnamed: 0', 'CleanDate', 'Y', 'Title', 'DevDate', 'Genre','imdbtag', 'Type',
       'Country', 'Originals', 'Rating', 'N_Ratings']
df = df.reindex(columns=cols)

In [55]:
# make sure the columns are formatted correctly
df.head(10)

,Unnamed: 0,CleanDate,Y,Title,DevDate,Genre,imdbtag,Type,Country,Originals,Rating,N_Ratings
0,2,2020-01-24,2020.0,A Sun,2019,Dramas,tt10883506,movies,at,1,8.0,326.0
1,2,2020-01-24,2020.0,A Sun,2019,Independent Movies,tt10883506,movies,at,1,8.0,326.0
2,2,2020-01-24,2020.0,A Sun,2019,International Movies,tt10883506,movies,at,1,8.0,326.0
3,4145,NaT,NaN,A Sun,2019,Dramas,tt10883506,movies,br,1,8.0,326.0
4,4145,NaT,NaN,A Sun,2019,Independent Movies,tt10883506,movies,br,1,8.0,326.0
5,4145,NaT,NaN,A Sun,2019,International Movies,tt10883506,movies,br,1,8.0,326.0
6,12553,2020-01-24,2020.0,A Sun,2019,Dramas,tt10883506,movies,dk,1,8.0,326.0
7,12553,2020-01-24,2020.0,A Sun,2019,Independent Movies,tt10883506,movies,dk,1,8.0,326.0
8,12553,2020-01-24,2020.0,A Sun,2019,International Movies,tt10883506,movies,dk,1,8.0,326.0
9,19748,2020-01-24,2020.0,A Sun,2019,Dramas,tt10883506,movies,fi,1,8.0,326.0

In [56]:
# get average ratings for all content, all original content, and all licensed content
avgREverything = df.Rating.mean()
avgRAllOriginals = df[df['Originals'] == 1].Rating.mean()
avgRAllLicensed = df[df['Originals'] == 0].Rating.mean()

In [57]:
# get average ratings for original vs. licensed movies and TV
avgROriginalMovies = df[(df['Originals'] == 1) & (df['Type'] == 'movies')].Rating.mean()
avgROriginalTV = df[(df['Originals'] == 1) & (df['Type'] == 'tvshows')].Rating.mean()
avgRLicensedMovies = df[(df['Originals'] == 0) & (df['Type'] == 'movies')].Rating.mean()
avgRLicensedTV = df[(df['Originals'] == 0) & (df['Type'] == 'tvshows')].Rating.mean()

In [58]:
# HYPOTHESIS 1: Netflix originals have higher IMDB ratings than other non-original shows on Netflix

In [59]:
# average rating of the entire dataset
avgREverything

6.630430920431134

In [60]:
# average rating for all Netflix original content
avgRAllOriginals

6.918253630673347

In [61]:
# average rating for all licensed content
avgRAllLicensed

6.500491043261357

In [62]:
# average rating for Netflix original movies
avgROriginalMovies

6.824673899792817

In [63]:
# average rating for Netflix original TV shows
avgROriginalTV

7.011255149018706

In [64]:
# average rating for licensed movies
avgRLicensedMovies

6.430578093306254

In [65]:
# average rating for licensed TV shows
avgRLicensedTV

6.582884121197618

In [66]:
# CONCLUSION #1: NETFLIX ORIGINALS HAVE HIGHER RATINGS THAN LICENSED CONTENT

In [67]:
# HYPOTHESIS 2: Netflix original content only has higher ratings because it tends to be within specific genres that are more popular

In [68]:
# see the average rating of each genre for licensed vs original content
df.groupby(['Genre','Originals']).agg({'Rating':['mean']})

                                          Rating
                                            mean
Genre                        Originals
Action & Adventure           0          5.870451
                             1          6.543363
Anime Features               0          6.075294
Anime Series                 0          7.487047
                             1          7.414146
British TV Shows             0          7.297482
                             1          7.527891
Children & Family Movies     0          5.759858
                             1          5.481518
Classic & Cult TV            0          7.364706
Classic Movies               0          8.188889
                             1          7.366667
Comedies                     0          5.567612
                             1          5.766138
Crime TV Shows               0          7.493537
                             1          7.605034
Cult Movies                  0          5.645455
                             1          7.211765
Documentaries                0          6.678261
                             1          6.825424
Docuseries                   0          7.554941
                             1          7.593761
Dramas                       0          6.360804
                             1          6.397842
Faith & Spirituality         0          5.751648
Horror Movies                0          5.277056
                             1          5.564198
Independent Movies           0          5.969839
                             1          6.158484
International Movies         0          6.032509
...                                          ...
Sci-Fi & Fantasy             1          7.032308
Science & Nature TV          0          6.900000
                             1          7.070270
Spanish-Language TV Shows    0          7.049364
                             1          7.506707
Sports Movies                0          6.358990
                             1          6.768148
Stand-Up Comedy              0          6.820638
                             1          6.673333
Stand-Up Comedy & Talk Shows 0          6.257857
                             1          7.733333
TV Action & Adventure        0          8.094660
                             1          7.666667
TV Comedies                  0          6.691119
                             1          7.382407
TV Dramas                    0          7.230069
                             1          7.245057
TV Horror                    0          7.107117
                             1          7.368667
TV Mysteries                 0          7.452555
                             1          6.585477
TV Sci-Fi & Fantasy          0          7.983562
                             1          7.343574
TV Shows                     1          7.800000
TV Thrillers                 0          7.889500
                             1          6.747393
Teen TV Shows                0          6.700000
                             1          7.551724
Thrillers                    0          5.818438
                             1          6.531923

[80 rows x 1 columns]

In [69]:
# if we wanted to be more thorough and scientific, we could run a regression analysis to see the effect that a genre has on a rating
# anecdotally though, it looks like Netflix original content is better than licensed content no matter the genre (with a few exceptions)

In [70]:
# CONCLUSION: NETFLIX CONTENT IS BETTER ACROSS MOST GENRES

In [ ]:
# HYPOTHESIS 3: Netflix originals are more popular than non-original counterparts because they are made in line with changing genre preferences
# note: hypothesis 2 has already been disproven, so we will just look at how genre preferences have changed over time

In [71]:
df.groupby(['Genre','DevDate']).agg({'Rating':['mean']})

                              Rating
                                mean
Genre              DevDate
Action & Adventure 1975     8.200000
                   1978     6.300000
                   1979     6.600000
                   1983     6.050000
                   1985     5.500000
                   1990     7.600000
                   1995     6.860000
                   1996     6.500000
                   1997     6.569231
                   1998     6.200000
                   1999     6.600000
                   2000     5.500000
                   2002     7.000000
                   2003     8.551613
                   2004     5.100000
                   2005     7.718750
                   2006     7.200000
                   2007     5.927273
                   2008     6.952459
                   2009     6.543750
                   2010     6.075926
                   2011     6.320000
                   2012     3.577500
                   2013     5.052222
                   2014     5.082857
                   2015     6.475410
                   2016     5.906863
                   2017     6.124742
                   2018     5.598485
                   2019     5.485586
...                              ...
TV Thrillers       2013     9.500000
                   2015     7.100000
                   2016     8.100000
                   2018     7.511628
                   2019     6.909251
Teen TV Shows      2012     7.400000
                   2014     8.700000
                   2015     7.000000
                   2016     7.566667
                   2017     6.000000
                   2019     7.427660
Thrillers          1985     6.600000
                   1997     7.088889
                   1998     7.100000
                   2000     6.600000
                   2002     7.100000
                   2004     7.600000
                   2006     7.200000
                   2007     6.300000
                   2009     4.740000
                   2010     7.000000
                   2011     5.653333
                   2013     5.877778
                   2014     5.842857
                   2015     6.576471
                   2016     6.037179
                   2017     5.897203
                   2018     5.783071
                   2019     6.250000
                   2020     5.900000

[549 rows x 1 columns]

In [160]:
# put it in a format that's more intuitive to read
byYear = df.groupby(['Genre','DevDate'],as_index=False).agg({'Rating':['mean']})
byYear.columns = byYear.columns.droplevel(1)
byYear.pivot(index='Genre',columns='DevDate')

                             Rating                                       \
DevDate                        1975      1978 1979  1983      1985  1990
Genre
Action & Adventure              8.2  6.300000  6.6  6.05  5.500000  7.60
Anime Features                  NaN       NaN  NaN   NaN       NaN   NaN
Anime Series                    NaN       NaN  NaN   NaN       NaN   NaN
British TV Shows                NaN       NaN  NaN   NaN       NaN   NaN
Children & Family Movies        NaN  5.100000  NaN   NaN       NaN   NaN
Classic & Cult TV               NaN       NaN  NaN   NaN       NaN  8.00
Classic Movies                  8.2       NaN  6.6   NaN       NaN   NaN
Comedies                        8.2       NaN  NaN   NaN  5.925000  7.20
Crime TV Shows                  NaN       NaN  NaN   NaN       NaN   NaN
Cult Movies                     NaN       NaN  6.6   NaN       NaN   NaN
Documentaries                   NaN       NaN  NaN   NaN       NaN   NaN
Docuseries                      NaN       NaN  NaN   NaN       NaN   NaN
Dramas                          NaN  6.700000  NaN   NaN  7.200000  7.36
Faith & Spirituality            NaN       NaN  NaN   NaN       NaN   NaN
Horror Movies                   NaN       NaN  NaN   NaN  6.600000   NaN
Independent Movies              NaN  6.700000  NaN   NaN  7.200000  7.20
International Movies            NaN  6.433333  NaN  6.05  5.866667  7.60
International TV Shows          NaN       NaN  NaN   NaN       NaN   NaN
Kids' TV                        NaN       NaN  NaN   NaN       NaN  8.00
Korean TV Shows                 NaN       NaN  NaN   NaN       NaN   NaN
LGBTQ Movies                    NaN       NaN  NaN   NaN       NaN   NaN
Movies                          NaN       NaN  NaN   NaN       NaN   NaN
Music & Musicals                NaN       NaN  NaN   NaN       NaN   NaN
Reality TV                      NaN       NaN  NaN   NaN       NaN   NaN
Romantic Movies                 NaN       NaN  NaN  6.00       NaN   NaN
Romantic TV Shows               NaN       NaN  NaN   NaN       NaN   NaN
Sci-Fi & Fantasy                NaN       NaN  NaN   NaN       NaN   NaN
Science & Nature TV             NaN       NaN  NaN   NaN       NaN   NaN
Spanish-Language TV Shows       NaN       NaN  NaN   NaN       NaN   NaN
Sports Movies                   NaN       NaN  NaN   NaN       NaN   NaN
Stand-Up Comedy                 NaN       NaN  NaN   NaN       NaN  6.00
Stand-Up Comedy & Talk Shows    NaN       NaN  NaN   NaN       NaN   NaN
TV Action & Adventure           NaN       NaN  NaN   NaN       NaN   NaN
TV Comedies                     NaN       NaN  NaN   NaN       NaN  8.00
TV Dramas                       NaN       NaN  NaN   NaN       NaN   NaN
TV Horror                       NaN       NaN  NaN   NaN       NaN   NaN
TV Mysteries                    NaN       NaN  NaN   NaN       NaN   NaN
TV Sci-Fi & Fantasy             NaN       NaN  NaN   NaN       NaN   NaN
TV Shows                        NaN       NaN  NaN   NaN       NaN   NaN
TV Thrillers                    NaN       NaN  NaN   NaN       NaN   NaN
Teen TV Shows                   NaN       NaN  NaN   NaN       NaN   NaN
Thrillers                       NaN       NaN  NaN   NaN  6.600000   NaN

                                                                  ...       \
DevDate                           1995      1996      1997  1998  ... 1967
Genre                                                             ...
Action & Adventure            6.860000  6.500000  6.569231  6.20  ...  NaN
Anime Features                     NaN       NaN       NaN   NaN  ...  NaN
Anime Series                       NaN       NaN  7.400000   NaN  ...  NaN
British TV Shows                   NaN       NaN       NaN   NaN  ...  NaN
Children & Family Movies           NaN  6.400000       NaN   NaN  ...  NaN
Classic & Cult TV                  NaN       NaN       NaN   NaN  ...  NaN
Classic Movies                     NaN       NaN       NaN   NaN  ...  7.1
Comedies                      6.900000  6.400000  6.000000  6.20  ...  NaN
Crime TV Shows                     NaN       NaN       NaN   NaN  ...  NaN
Cult Movies                        NaN       NaN       NaN  7.10  ...  NaN
Documentaries                      NaN       NaN       NaN   NaN  ...  NaN
Docuseries                         NaN       NaN       NaN   NaN  ...  NaN
Dramas                        6.300000  8.000000  7.376471  7.34  ...  7.1
Faith & Spirituality               NaN       NaN       NaN   NaN  ...  NaN
Horror Movies                      NaN       NaN  6.200000   NaN  ...  NaN
Independent Movies            6.900000  8.000000       NaN   NaN  ...  NaN
International Movies               NaN       NaN  6.450000  7.40  ...  7.1
International TV Shows             NaN       NaN       NaN   NaN  ...  NaN
Kids' TV                      7.700000       NaN  7.400000  7.70  ...  NaN
Korean TV Shows                    NaN       NaN       NaN   NaN  ...  NaN
LGBTQ Movies                       NaN       NaN       NaN   NaN  ...  NaN
Movies                             NaN       NaN       NaN   NaN  ...  NaN
Music & Musicals                   NaN       NaN  6.000000   NaN  ...  NaN
Reality TV                         NaN       NaN       NaN   NaN  ...  NaN
Romantic Movies               6.882857       NaN  6.200000   NaN  ...  NaN
Romantic TV Shows                  NaN       NaN       NaN   NaN  ...  NaN
Sci-Fi & Fantasy              6.600000  6.404167       NaN  6.20  ...  NaN
Science & Nature TV                NaN       NaN       NaN   NaN  ...  NaN
Spanish-Language TV Shows          NaN       NaN       NaN   NaN  ...  NaN
Sports Movies                      NaN       NaN       NaN   NaN  ...  NaN
Stand-Up Comedy                    NaN       NaN       NaN   NaN  ...  NaN
Stand-Up Comedy & Talk Shows       NaN       NaN       NaN   NaN  ...  NaN
TV Action & Adventure              NaN       NaN       NaN   NaN  ...  NaN
TV Comedies                        NaN       NaN       NaN   NaN  ...  NaN
TV Dramas                          NaN       NaN       NaN   NaN  ...  NaN
TV Horror                          NaN       NaN       NaN   NaN  ...  NaN
TV Mysteries                       NaN       NaN       NaN   NaN  ...  NaN
TV Sci-Fi & Fantasy                NaN       NaN       NaN   NaN  ...  NaN
TV Shows                           NaN       NaN       NaN   NaN  ...  NaN
TV Thrillers                  7.700000       NaN       NaN  7.70  ...  NaN
Teen TV Shows                      NaN       NaN       NaN   NaN  ...  NaN
Thrillers                          NaN       NaN  7.088889  7.10  ...  NaN


DevDate                      1972 1993 1962  1974 1981 1988 1989 1987 1991
Genre
Action & Adventure            NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Anime Features                NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Anime Series                  NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
British TV Shows              NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Children & Family Movies      NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Classic & Cult TV             NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Classic Movies                8.6  8.0  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Comedies                      NaN  8.0  7.1  7.40  5.3  7.6  NaN  NaN  NaN
Crime TV Shows                NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Cult Movies                   NaN  8.0  NaN   NaN  NaN  7.6  NaN  NaN  NaN
Documentaries                 NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Docuseries                    NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Dramas                        8.6  NaN  7.1  7.04  NaN  NaN  7.2  NaN  NaN
Faith & Spirituality          NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Horror Movies                 NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Independent Movies            NaN  NaN  NaN  7.40  NaN  NaN  NaN  NaN  NaN
International Movies          8.6  NaN  7.1  5.60  5.3  NaN  7.2  NaN  NaN
International TV Shows        NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Kids' TV                      NaN  6.2  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Korean TV Shows               NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
LGBTQ Movies                  NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Movies                        NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Music & Musicals              NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Reality TV                    NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Romantic Movies               NaN  NaN  NaN  5.60  NaN  NaN  NaN  NaN  NaN
Romantic TV Shows             NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Sci-Fi & Fantasy              NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Science & Nature TV           NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Spanish-Language TV Shows     NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Sports Movies                 NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Stand-Up Comedy               NaN  NaN  NaN   NaN  NaN  NaN  8.5  7.3  8.3
Stand-Up Comedy & Talk Shows  NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Action & Adventure         NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Comedies                   NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Dramas                     NaN  8.4  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Horror                     NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Mysteries                  NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Sci-Fi & Fantasy           NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Shows                      NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
TV Thrillers                  NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Teen TV Shows                 NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN
Thrillers                     NaN  NaN  NaN   NaN  NaN  NaN  NaN  NaN  NaN

[42 rows x 45 columns]

In [ ]:
# CONCLUSION: Genre preferences change quite a bit over time. anecdotally, no trends can be identified

In [ ]:
# EXPERIMENTATION BELOW, NOT PART OF ORIGINAL HYPOTHESES

In [28]:
# what is the best content on Netflix worldwide?
df.sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(20)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
135895,135895,2013-02-08,2013.0,Breaking Bad,2013,tt0903747,tvshows,us,0,9.5,1303196.0
133226,133226,2018-11-06,2018.0,Planet Earth II,2016,tt5491994,tvshows,uk,0,9.5,83871.0
133353,133353,2018-03-30,2018.0,Planet Earth: The Complete Collection,2006,tt0795176,tvshows,uk,0,9.4,156531.0
132547,132547,2019-10-06,2019.0,Blue Planet II,2017,tt6769208,tvshows,uk,0,9.4,26376.0
54268,54268,2019-05-04,2019.0,Gezegenimiz,2019,tt9253866,movies,tr,1,9.3,21242.0
12624,12624,2020-01-01,2020.0,En verden udenfor,1994,tt0111161,movies,dk,0,9.3,2183286.0
82047,82047,2018-09-15,2018.0,Les Evadés,1994,tt0111161,tvshows,fr,0,9.3,2183286.0
12703,12703,2019-12-22,2019.0,Rick and Morty,2019,tt2861424,movies,dk,0,9.3,317362.0
17422,17422,2019-05-04,2019.0,Nuestro planeta,2019,tt9253866,movies,es,1,9.3,21242.0
82767,82767,2017-04-11,2017.0,Rick et Morty,2017,tt2861424,tvshows,fr,0,9.3,317362.0
105917,105917,NaT,NaN,Nyckeln till frihet,1994,tt0111161,tvshows,se,0,9.3,2183286.0
53010,53010,2020-01-01,2020.0,Esaretin Bedeli,1994,tt0111161,movies,tr,0,9.3,2183286.0
85180,85180,2019-05-04,2019.0,Il nostro pianeta,2019,tt9253866,tvshows,it,1,9.3,21242.0
107148,107148,2019-05-04,2019.0,Our Planet,2019,tt9253866,tvshows,se,1,9.3,21242.0
84457,84457,2019-09-18,2019.0,Le ali della libertà,1994,tt0111161,tvshows,it,0,9.3,2183286.0
39084,39084,2020-01-01,2020.0,Frihetens regn,1994,tt0111161,movies,no,0,9.3,2183286.0
21066,21066,2019-05-04,2019.0,Our Planet: Uskomaton planeettamme,2019,tt9253866,movies,fi,1,9.3,21242.0
103063,103063,2019-10-15,2019.0,Um sonho de liberdade,1994,tt0111161,tvshows,pt,0,9.3,2183286.0
47358,47358,2019-05-04,2019.0,Nosso Planeta,2019,tt9253866,movies,pt,1,9.3,21242.0
91982,91982,2019-12-22,2019.0,Rick en Morty,2019,tt2861424,tvshows,nl,0,9.3,317362.0

In [29]:
# what is the best Netflix original content worldwide?
df[df['Originals'] == 1].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(20)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
81248,81248,2019-05-04,2019.0,Notre planète,2019,tt9253866,tvshows,fr,1,9.3,21242.0
107148,107148,2019-05-04,2019.0,Our Planet,2019,tt9253866,tvshows,se,1,9.3,21242.0
100352,100352,2019-05-04,2019.0,Nasza planeta,2019,tt9253866,tvshows,pl,1,9.3,21242.0
88964,88964,2019-05-04,2019.0,Nuestro planeta,2019,tt9253866,tvshows,mx,1,9.3,21242.0
66481,66481,2019-05-04,2019.0,Unser Planet,2019,tt9253866,tvshows,de,1,9.3,21242.0
54268,54268,2019-05-04,2019.0,Gezegenimiz,2019,tt9253866,movies,tr,1,9.3,21242.0
85180,85180,2019-05-04,2019.0,Il nostro pianeta,2019,tt9253866,tvshows,it,1,9.3,21242.0
5702,5702,2019-05-04,2019.0,Nosso Planeta,2019,tt9253866,movies,br,1,9.3,21242.0
77579,77579,2019-05-04,2019.0,Our Planet: Uskomaton planeettamme,2019,tt9253866,tvshows,fi,1,9.3,21242.0
40304,40304,2019-05-04,2019.0,Our Planet – Vårt utrolige hjem,2019,tt9253866,movies,no,1,9.3,21242.0
134269,134269,2019-01-10,2019.0,College Romance,2018,tt8809646,tvshows,us,1,9.2,19037.0
5476,5476,2019-05-31,2019.0,Olhos que Condenam,2019,tt7137906,movies,br,1,9.0,59839.0
43696,43696,2019-05-31,2019.0,Jak nas widzą,2019,tt7137906,movies,pl,1,9.0,59839.0
36440,36440,2019-05-31,2019.0,When They See Us,2019,tt7137906,movies,nl,1,9.0,59839.0
132677,132677,2019-01-04,2019.0,Peasants Rebellion,2018,tt9011036,tvshows,uk,1,9.0,57.0
120590,120590,2020-01-21,2020.0,KD (A) Karuppudurai,2019,tt8747560,movies,uk,1,9.0,171.0
32264,32264,2019-05-31,2019.0,Así nos ven,2019,tt7137906,movies,mx,1,9.0,59839.0
24514,24514,2019-05-31,2019.0,Dans leur regard,2019,tt7137906,movies,fr,1,9.0,59839.0
45124,45124,2018-05-01,2018.0,Władca Pierścieni: Powrót króla,2003,tt0167260,movies,pl,1,8.9,1553201.0
132423,132423,2019-01-08,2019.0,Regiment Diaries,2018,tt9642576,tvshows,uk,1,8.9,27.0

In [30]:
# what is the best licensed content worldwide?
df[df['Originals'] == 0].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(20)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
135895,135895,2013-02-08,2013.0,Breaking Bad,2013,tt0903747,tvshows,us,0,9.5,1303196.0
133226,133226,2018-11-06,2018.0,Planet Earth II,2016,tt5491994,tvshows,uk,0,9.5,83871.0
133353,133353,2018-03-30,2018.0,Planet Earth: The Complete Collection,2006,tt0795176,tvshows,uk,0,9.4,156531.0
132547,132547,2019-10-06,2019.0,Blue Planet II,2017,tt6769208,tvshows,uk,0,9.4,26376.0
67925,67925,2018-01-29,2018.0,Rick and Morty,2017,tt2861424,tvshows,de,0,9.3,317362.0
18480,18480,2018-03-19,2018.0,Rick y Morty,2017,tt2861424,movies,es,0,9.3,317362.0
26294,26294,2017-04-11,2017.0,Rick et Morty,2017,tt2861424,movies,fr,0,9.3,317362.0
35461,35461,NaT,NaN,The Shawshank Redemption,1994,tt0111161,movies,nl,0,9.3,2183286.0
35509,35509,2019-12-22,2019.0,Rick en Morty,2019,tt2861424,movies,nl,0,9.3,317362.0
95557,95557,2020-01-01,2020.0,Frihetens regn,1994,tt0111161,tvshows,no,0,9.3,2183286.0
27984,27984,2019-09-18,2019.0,Le ali della libertà,1994,tt0111161,movies,it,0,9.3,2183286.0
105917,105917,NaT,NaN,Nyckeln till frihet,1994,tt0111161,tvshows,se,0,9.3,2183286.0
103063,103063,2019-10-15,2019.0,Um sonho de liberdade,1994,tt0111161,tvshows,pt,0,9.3,2183286.0
69137,69137,2020-01-01,2020.0,En verden udenfor,1994,tt0111161,tvshows,dk,0,9.3,2183286.0
25574,25574,2018-09-15,2018.0,Les Evadés,1994,tt0111161,movies,fr,0,9.3,2183286.0
19847,19847,2020-01-01,2020.0,Rita Hayworth - avain pakoon,1994,tt0111161,movies,fi,0,9.3,2183286.0
133362,133362,2018-03-30,2018.0,The Hunt,2015,tt5167198,tvshows,uk,0,9.3,3359.0
109483,109483,2020-01-01,2020.0,Esaretin Bedeli,1994,tt0111161,tvshows,tr,0,9.3,2183286.0
34072,34072,2018-08-02,2018.0,Avatar: la leyenda de Aang,2007,tt0417299,movies,mx,0,9.2,205921.0
69351,69351,2019-01-12,2019.0,The Godfather,1972,tt0068646,tvshows,dk,0,9.2,1504043.0

In [34]:
# US ONLY for the next few queries
# what is the best content on Netflix in the US?
df[df['Country'] == 'us'].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(10)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
135895,135895,2013-02-08,2013.0,Breaking Bad,2013,tt0903747,tvshows,us,0,9.5,1303196.0
134649,134649,2019-05-04,2019.0,Our Planet,2019,tt9253866,tvshows,us,1,9.3,21242.0
134269,134269,2019-01-10,2019.0,College Romance,2018,tt8809646,tvshows,us,1,9.2,19037.0
135055,135055,2018-01-09,2018.0,Age of Rebellion,2018,tt8931836,tvshows,us,0,9.2,30.0
135066,135066,2018-08-31,2018.0,Yeh Meri Family,2018,tt8595766,tvshows,us,0,9.2,16516.0
135311,135311,2018-01-01,2018.0,Fullmetal Alchemist: Brotherhood,2010,tt1355642,tvshows,us,0,9.1,99203.0
135592,135592,2017-04-15,2017.0,Leyla and Mecnun,2014,tt1831164,tvshows,us,0,9.1,84913.0
135143,135143,2018-06-20,2018.0,The Vietnam War: A Film by Ken Burns and Lynn ...,2017,tt1877514,tvshows,us,0,9.1,15456.0
126990,126990,2018-01-03,2018.0,Hans Zimmer: Live in Prague,2017,tt5732482,movies,us,0,9.1,2060.0
126742,126742,2018-01-06,2018.0,Natsamrat - Asa Nat Hone Nahi,2016,tt5311546,movies,us,0,9.1,4503.0

In [39]:
# what is the best Netflix original content on Netflix in the US?
df[(df['Country'] == 'us') & (df['Originals'] == 1)].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(10)
# NOTE: there are some errors in the data, e.g. Lord of the Rings is definitely not a Netflix original

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
134649,134649,2019-05-04,2019.0,Our Planet,2019,tt9253866,tvshows,us,1,9.3,21242.0
134269,134269,2019-01-10,2019.0,College Romance,2018,tt8809646,tvshows,us,1,9.2,19037.0
124447,124447,2020-01-21,2020.0,KD (A) Karuppudurai,2019,tt8747560,movies,us,1,9.0,171.0
134661,134661,2019-01-04,2019.0,Peasants Rebellion,2018,tt9011036,tvshows,us,1,9.0,57.0
134547,134547,2019-05-31,2019.0,When They See Us,2019,tt7137906,tvshows,us,1,9.0,59839.0
134404,134404,2019-01-08,2019.0,Regiment Diaries,2018,tt9642576,tvshows,us,1,8.9,27.0
124576,124576,2020-01-01,2020.0,The Lord of the Rings: The Return of the King,2003,tt0167260,movies,us,1,8.9,1553201.0
134161,134161,2019-08-11,2019.0,Greatest Events of WWII in Colour,2019,tt9103932,tvshows,us,1,8.8,1979.0
134217,134217,2019-10-25,2019.0,The Untamed,2019,tt10554898,tvshows,us,1,8.8,620.0
134467,134467,2019-04-07,2019.0,Stranger Things,2019,tt4574334,tvshows,us,1,8.8,701022.0

In [38]:
# what is the best licensed content on Netflix in the US?
df[(df['Country'] == 'us') & (df['Originals'] == 0)].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(10)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
135895,135895,2013-02-08,2013.0,Breaking Bad,2013,tt0903747,tvshows,us,0,9.5,1303196.0
135066,135066,2018-08-31,2018.0,Yeh Meri Family,2018,tt8595766,tvshows,us,0,9.2,16516.0
135055,135055,2018-01-09,2018.0,Age of Rebellion,2018,tt8931836,tvshows,us,0,9.2,30.0
126742,126742,2018-01-06,2018.0,Natsamrat - Asa Nat Hone Nahi,2016,tt5311546,movies,us,0,9.1,4503.0
126990,126990,2018-01-03,2018.0,Hans Zimmer: Live in Prague,2017,tt5732482,movies,us,0,9.1,2060.0
135592,135592,2017-04-15,2017.0,Leyla and Mecnun,2014,tt1831164,tvshows,us,0,9.1,84913.0
135570,135570,2017-05-15,2017.0,Sherlock,2017,tt1475582,tvshows,us,0,9.1,742814.0
135311,135311,2018-01-01,2018.0,Fullmetal Alchemist: Brotherhood,2010,tt1355642,tvshows,us,0,9.1,99203.0
135143,135143,2018-06-20,2018.0,The Vietnam War: A Film by Ken Burns and Lynn ...,2017,tt1877514,tvshows,us,0,9.1,15456.0
135006,135006,2018-01-10,2018.0,Still Game,2016,tt0281491,tvshows,us,0,9.0,4766.0

In [41]:
# what are the best Netflix original movies on Netflix in the US?
df[(df['Country'] == 'us') & (df['Originals'] == 1) & (df['Type'] == 'movies')].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(10)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
124447,124447,2020-01-21,2020.0,KD (A) Karuppudurai,2019,tt8747560,movies,us,1,9.0,171.0
124576,124576,2020-01-01,2020.0,The Lord of the Rings: The Return of the King,2003,tt0167260,movies,us,1,8.9,1553201.0
124527,124527,2020-01-01,2020.0,Inception,2010,tt1375666,movies,us,1,8.8,1915095.0
124877,124877,2019-04-11,2019.0,Oththa Seruppu Size 7,2019,tt10370116,movies,us,1,8.7,1350.0
124922,124922,2019-01-11,2019.0,The Matrix,1999,tt0133093,movies,us,1,8.7,1571978.0
124577,124577,2020-01-01,2020.0,The Lord of the Rings: The Two Towers,2002,tt0167261,movies,us,1,8.7,1402043.0
124624,124624,2019-12-31,2019.0,Gol Maal,1979,tt0079221,movies,us,1,8.6,16309.0
124501,124501,2020-01-01,2020.0,City of God,2002,tt0317248,movies,us,1,8.6,665034.0
124638,124638,2019-12-31,2019.0,Koshish,1972,tt0215911,movies,us,1,8.6,1337.0
124771,124771,2019-01-12,2019.0,The Departed,2006,tt0407887,movies,us,1,8.5,1116573.0

In [42]:
# what are the best licensed movies on Netflix in the US?
df[(df['Country'] == 'us') & (df['Originals'] == 0) & (df['Type'] == 'movies')].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(10)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
126742,126742,2018-01-06,2018.0,Natsamrat - Asa Nat Hone Nahi,2016,tt5311546,movies,us,0,9.1,4503.0
126990,126990,2018-01-03,2018.0,Hans Zimmer: Live in Prague,2017,tt5732482,movies,us,0,9.1,2060.0
125310,125310,2019-06-26,2019.0,Unbroken,2019,tt9663460,movies,us,0,9.0,445.0
126554,126554,2018-01-08,2018.0,Mahabharat,2013,tt3212600,movies,us,0,8.8,3275.0
125815,125815,2019-02-15,2019.0,Ayana,2017,tt6891660,movies,us,0,8.8,90.0
125969,125969,2019-01-01,2019.0,Merku Thodarchi Malai,2018,tt7794052,movies,us,0,8.8,1358.0
125644,125644,2019-01-04,2019.0,The World's Most Wanted Animal,2018,tt8653894,movies,us,0,8.8,31.0
126649,126649,2018-06-07,2018.0,Luciano Mellera: Infantiloide,2018,tt7607400,movies,us,0,8.7,1471.0
127914,127914,2017-02-28,2017.0,Be Here Now,2015,tt2473476,movies,us,0,8.7,2980.0
127218,127218,2017-01-12,2017.0,Eh Janam Tumhare Lekhe,2015,tt4280824,movies,us,0,8.7,333.0

In [43]:
# what are the best Netflix original TV shows on Netflix in the US?
df[(df['Country'] == 'us') & (df['Originals'] == 1) & (df['Type'] == 'tvshows')].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(10)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
134649,134649,2019-05-04,2019.0,Our Planet,2019,tt9253866,tvshows,us,1,9.3,21242.0
134269,134269,2019-01-10,2019.0,College Romance,2018,tt8809646,tvshows,us,1,9.2,19037.0
134547,134547,2019-05-31,2019.0,When They See Us,2019,tt7137906,tvshows,us,1,9.0,59839.0
134661,134661,2019-01-04,2019.0,Peasants Rebellion,2018,tt9011036,tvshows,us,1,9.0,57.0
134404,134404,2019-01-08,2019.0,Regiment Diaries,2018,tt9642576,tvshows,us,1,8.9,27.0
134467,134467,2019-04-07,2019.0,Stranger Things,2019,tt4574334,tvshows,us,1,8.8,701022.0
134023,134023,2020-04-01,2020.0,Go! Go! Cory Carson,2020,tt8115702,tvshows,us,1,8.8,31.0
134371,134371,2019-08-15,2019.0,Sacred Games,2019,tt6077448,tvshows,us,1,8.8,63593.0
134314,134314,2019-09-15,2019.0,The Universe,2009,tt1051155,tvshows,us,1,8.8,4756.0
134275,134275,2019-01-10,2019.0,Signal,2016,tt5332206,tvshows,us,1,8.8,2190.0

In [44]:
# what are the best licensed TV shows on Netflix in the US?
df[(df['Country'] == 'us') & (df['Originals'] == 0) & (df['Type'] == 'tvshows')].sort_values('Rating',ascending=False).drop_duplicates(['Title']).head(10)

,Unnamed: 0,CleanDate,Y,Title,DevDate,imdbtag,Type,Country,Originals,Rating,N_Ratings
135895,135895,2013-02-08,2013.0,Breaking Bad,2013,tt0903747,tvshows,us,0,9.5,1303196.0
135066,135066,2018-08-31,2018.0,Yeh Meri Family,2018,tt8595766,tvshows,us,0,9.2,16516.0
135055,135055,2018-01-09,2018.0,Age of Rebellion,2018,tt8931836,tvshows,us,0,9.2,30.0
135592,135592,2017-04-15,2017.0,Leyla and Mecnun,2014,tt1831164,tvshows,us,0,9.1,84913.0
135143,135143,2018-06-20,2018.0,The Vietnam War: A Film by Ken Burns and Lynn ...,2017,tt1877514,tvshows,us,0,9.1,15456.0
135311,135311,2018-01-01,2018.0,Fullmetal Alchemist: Brotherhood,2010,tt1355642,tvshows,us,0,9.1,99203.0
135570,135570,2017-05-15,2017.0,Sherlock,2017,tt1475582,tvshows,us,0,9.1,742814.0
135690,135690,2016-12-15,2016.0,Humsafar,2011,tt2403201,tvshows,us,0,9.0,3066.0
135698,135698,2016-12-15,2016.0,Zindagi Gulzar Hai,2012,tt2828240,tvshows,us,0,9.0,2534.0
135653,135653,2017-02-22,2017.0,The War: A Film by Ken Burns and Lynn Novick,2007,tt0996994,tvshows,us,0,9.0,4404.0

In [80]:
# what are the years that produced the best content worldwide?
df.groupby(['DevDate'])['Rating'].mean().nlargest(10)

DevDate
1941    8.300000
1958    8.300000
1974    8.290476
1972    8.270968
1939    8.050000
1968    8.036364
1955    8.000000
1936    7.900000
1952    7.900000
1979    7.809868
Name: Rating, dtype: float64

In [ ]:
# NOTE: some years only have a handful of movies/TVshows, so we should only take years with >20 movies/TVshows. e.g. 1936 has 2 movies

In [73]:
# what are the years (with 20 or more entries) that produced the best content worldwide?
df.groupby('DevDate').filter(lambda x: len(x) >= 20).groupby(['DevDate'])['Rating'].mean().nlargest(10)

DevDate
1974    8.290476
1972    8.270968
1968    8.036364
1979    7.809868
1960    7.737500
1975    7.665476
1969    7.334783
1990    7.318824
1971    7.304762
1977    7.287629
Name: Rating, dtype: float64

In [74]:
# which countries have the best content?
df.groupby(['Country'])['Rating'].mean().nlargest(10)

Country
tr    6.680347
pt    6.675753
es    6.644062
at    6.631998
de    6.631145
pl    6.630285
fi    6.625428
dk    6.624187
it    6.623834
se    6.622116
Name: Rating, dtype: float64